baseurl = "https://by-dev.com/"
languageCode = "en-us"
title = "Around Programming Blog"
description = "a blog of developer"
copyright = "Copyright Â© 2019, Yuriy B; all rights reserved."
theme = "onepress"
tags = ["blog", "PHP", "Docker", "MySQL", "MongoDB", "Vue.js", "Linux", "Golang"]
# Enter your tracking code to enable Google Analytics
googleAnalytics = " "
# Disable comments by leaving disqusShortname empty
disqusShortname = "by-dev-blog"
canonifyURLS = true
paginate = 10
sectionPagesMenu = "main"

[params]
	author = "Yuriy Belyakov"
	bio = "Backend developer with a small mix of frontend"
	logo = "/img/onepress-logo.png"
	avatar = "/img/onepress-author.png"
	opengraphImage = "/img/onepress-logo.jpg"
	enableRSS = true

	customCSS = false
	readMore = "Read Up"
    
    # Social
	github = "https://github.com/neo-classic"
	linkedin = "https://www.linkedin.com/in/yuriy-belyakov-a6154749"
	twitter  = "https://twitter.com/BelyakovYuri"
	facebook  = "https://www.facebook.com/urij.belakov"

    
    # Widget
    widgets = true
    
    # Author box and Share button
    authorCard = false 
    shareButton = true
    
    # Code highlighting with highlight.js
    highlightJS = true

# Taxonomies
[taxonomies]
    tag = "tags"